### ISSUE TITLE
R requires additional packages not mentioned in the spec

### ISSUE THREAD

**Issue by kolovos** [georghinkel/ttc2017LiveContest#1]
Packages required
* jsonlite
* ggplot2

**Comment by georghinkel** [comment]
Yes. Thanks for pointing this out.

I added this requirement to the readme (7165b1946f8d29f950f0970dc82eb97ca425689e)

**Comment by kolovos** [comment]
Thanks Georg. It may also be worth noting that the benchmarking framework requires Windows to run (as it tries to execute NMFCodeGenerator.exe in line 75).
